# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser_lib

# Build rule for target.
parser_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser_lib
.PHONY : parser_lib

# fast build rule for target.
parser_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/build
.PHONY : parser_lib/fast

#=============================================================================
# Target rules for targets named calculator

# Build rule for target.
calculator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator
.PHONY : calculator

# fast build rule for target.
calculator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/build
.PHONY : calculator/fast

#=============================================================================
# Target rules for targets named test_until

# Build rule for target.
test_until: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_until
.PHONY : test_until

# fast build rule for target.
test_until/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_until.dir/build.make CMakeFiles/test_until.dir/build
.PHONY : test_until/fast

calc.o: calc.c.o
.PHONY : calc.o

# target to build an object file
calc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calc.c.o
.PHONY : calc.c.o

calc.i: calc.c.i
.PHONY : calc.i

# target to preprocess a source file
calc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calc.c.i
.PHONY : calc.c.i

calc.s: calc.c.s
.PHONY : calc.s

# target to generate assembly for a file
calc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calc.c.s
.PHONY : calc.c.s

combinators.o: combinators.c.o
.PHONY : combinators.o

# target to build an object file
combinators.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/combinators.c.o
.PHONY : combinators.c.o

combinators.i: combinators.c.i
.PHONY : combinators.i

# target to preprocess a source file
combinators.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/combinators.c.i
.PHONY : combinators.c.i

combinators.s: combinators.c.s
.PHONY : combinators.s

# target to generate assembly for a file
combinators.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/combinators.c.s
.PHONY : combinators.c.s

parser.o: parser.c.o
.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i
.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s
.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_lib.dir/build.make CMakeFiles/parser_lib.dir/parser.c.s
.PHONY : parser.c.s

test_until.o: test_until.c.o
.PHONY : test_until.o

# target to build an object file
test_until.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_until.dir/build.make CMakeFiles/test_until.dir/test_until.c.o
.PHONY : test_until.c.o

test_until.i: test_until.c.i
.PHONY : test_until.i

# target to preprocess a source file
test_until.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_until.dir/build.make CMakeFiles/test_until.dir/test_until.c.i
.PHONY : test_until.c.i

test_until.s: test_until.c.s
.PHONY : test_until.s

# target to generate assembly for a file
test_until.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_until.dir/build.make CMakeFiles/test_until.dir/test_until.c.s
.PHONY : test_until.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... calculator"
	@echo "... parser_lib"
	@echo "... test_until"
	@echo "... calc.o"
	@echo "... calc.i"
	@echo "... calc.s"
	@echo "... combinators.o"
	@echo "... combinators.i"
	@echo "... combinators.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... test_until.o"
	@echo "... test_until.i"
	@echo "... test_until.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
